name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Extract subscription ID from Azure credentials
      run: |
        SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r '.subscriptionId')
        echo "SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV

    - name: Extract parameters for resource group creation
      id: extract-params
      run: |
        NAME_PREFIX=$(jq -r '.parameters.namePrefix.value' infra/parameters.json)
        LOCATION=$(jq -r '.parameters.location.value' infra/parameters.json)
        echo "name-prefix=$NAME_PREFIX" >> $GITHUB_OUTPUT
        echo "location=$LOCATION" >> $GITHUB_OUTPUT
        echo "resource-group=rg-${NAME_PREFIX}" >> $GITHUB_OUTPUT

    - name: Create Resource Group
      run: |
        az group create \
          --name ${{ steps.extract-params.outputs.resource-group }} \
          --location ${{ steps.extract-params.outputs.location }}

    - name: Create secrets JSON from app secrets
      run: |
        echo '${{ secrets.APP_SECRETS }}' > infra/secrets.json

    - name: Deploy Bicep template
      uses: azure/arm-deploy@v1
      id: deploy-infra
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ steps.extract-params.outputs.resource-group }}
        template: infra/main.bicep
        parameters: infra/parameters.json

    - name: Build Docker image
      run: |
        docker build -f FestivalManagementWeb/Dockerfile -t ${{ steps.extract-params.outputs.name-prefix }}-app:${{ github.sha }} .

    - name: Get ACR credentials and login
      run: |
        ACR_PASSWORD=$(az acr credential show --name ${{ steps.deploy-infra.outputs.containerRegistryName }} --query "passwords[0].value" --output tsv)
        echo $ACR_PASSWORD | docker login ${{ steps.deploy-infra.outputs.containerRegistryLoginServer }} --username ${{ steps.deploy-infra.outputs.containerRegistryName }} --password-stdin

    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ steps.extract-params.outputs.name-prefix }}-app"
        docker tag $IMAGE_NAME:${{ github.sha }} ${{ steps.deploy-infra.outputs.containerRegistryLoginServer }}/$IMAGE_NAME:${{ github.sha }}
        docker tag $IMAGE_NAME:${{ github.sha }} ${{ steps.deploy-infra.outputs.containerRegistryLoginServer }}/$IMAGE_NAME:latest
        docker push ${{ steps.deploy-infra.outputs.containerRegistryLoginServer }}/$IMAGE_NAME:${{ github.sha }}
        docker push ${{ steps.deploy-infra.outputs.containerRegistryLoginServer }}/$IMAGE_NAME:latest

    - name: Update Container App
      run: |
        IMAGE_NAME="${{ steps.extract-params.outputs.name-prefix }}-app"
        az containerapp update \
          --name $IMAGE_NAME \
          --resource-group ${{ steps.extract-params.outputs.resource-group }} \
          --image ${{ steps.deploy-infra.outputs.containerRegistryLoginServer }}/$IMAGE_NAME:${{ github.sha }}

    - name: Output application URL
      run: |
        echo "Application deployed to: ${{ steps.deploy-infra.outputs.containerAppUrl }}"