name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az version

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Extract subscription ID from Azure credentials
      env:
        AZURE_CREDS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        SUBSCRIPTION_ID=$(echo "$AZURE_CREDS" | jq -r '.subscriptionId')
        echo "SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV

    - name: Extract parameters for resource group creation
      id: extract-params
      run: |
        NAME_PREFIX=$(jq -r '.parameters.namePrefix.value' infra/parameters.json)
        LOCATION=$(jq -r '.parameters.location.value' infra/parameters.json)

        # Validate required parameters
        if [ -z "$NAME_PREFIX" ] || [ "$NAME_PREFIX" = "null" ]; then
          echo "Error: namePrefix is required in parameters.json"
          exit 1
        fi
        if [ -z "$LOCATION" ] || [ "$LOCATION" = "null" ]; then
          echo "Error: location is required in parameters.json"
          exit 1
        fi

        REGISTRY_REPOSITORY=$(jq -r '.parameters.containerRegistryRepository.value // empty' infra/parameters.json 2>/dev/null)
        REGISTRY_SERVER=$(jq -r '.parameters.containerRegistryServer.value // empty' infra/parameters.json 2>/dev/null)
        if [ "$REGISTRY_REPOSITORY" = "null" ]; then
          REGISTRY_REPOSITORY=""
        fi
        if [ -z "$REGISTRY_REPOSITORY" ]; then
          REGISTRY_REPOSITORY="${GITHUB_REPOSITORY}"
          REGISTRY_REPOSITORY=$(echo "$REGISTRY_REPOSITORY" | tr '[:upper:]' '[:lower:]')
        fi
        if [ "$REGISTRY_SERVER" = "null" ] || [ -z "$REGISTRY_SERVER" ]; then
          REGISTRY_SERVER="ghcr.io"
        fi

        IMAGE_NAME="${NAME_PREFIX}-app"

        echo "name-prefix=$NAME_PREFIX" >> $GITHUB_OUTPUT
        echo "location=$LOCATION" >> $GITHUB_OUTPUT
        echo "resource-group=rg-${NAME_PREFIX}" >> $GITHUB_OUTPUT
        echo "container-registry-repository=$REGISTRY_REPOSITORY" >> $GITHUB_OUTPUT
        echo "container-registry-server=$REGISTRY_SERVER" >> $GITHUB_OUTPUT
        echo "image-name=$IMAGE_NAME" >> $GITHUB_OUTPUT

    - name: Create Resource Group
      run: |
        az group create \
          --name ${{ steps.extract-params.outputs.resource-group }} \
          --location ${{ steps.extract-params.outputs.location }}

    - name: Create secrets JSON from app secrets
      env:
        APP_SECRETS_JSON: ${{ secrets.APP_SECRETS }}
      run: |
        if [ -z "$APP_SECRETS_JSON" ]; then
          echo "Error: APP_SECRETS secret is not set"
          exit 1
        fi
        echo "$APP_SECRETS_JSON" > infra/secrets.json

        # Validate JSON structure
        if ! jq -e '.googleClientId' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'googleClientId'"
          exit 1
        fi
        if ! jq -e '.googleClientSecret' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'googleClientSecret'"
          exit 1
        fi
        if ! jq -e '.initialUserEmail' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'initialUserEmail'"
          exit 1
        fi
        if ! jq -e '.mongoAdminPassword' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'mongoAdminPassword'"
          exit 1
        fi
        if ! jq -e '.gitSettings.authorName' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'gitSettings.authorName'"
          exit 1
        fi
        if ! jq -e '.gitSettings.authorEmail' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'gitSettings.authorEmail'"
          exit 1
        fi
        if ! jq -e '.gitSettings.token' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'gitSettings.token'"
          exit 1
        fi
        if ! jq -e '.gitSettings.cloneUrl' infra/secrets.json > /dev/null; then
          echo "Error: APP_SECRETS must contain 'gitSettings.cloneUrl'"
          exit 1
        fi
        echo "All required secrets validated"

    - name: Extract secrets for Bicep parameters
      id: extract-secrets
      env:
        APP_SECRETS_JSON: ${{ secrets.APP_SECRETS }}
      run: |
        echo "google-client-id=$(echo "$APP_SECRETS_JSON" | jq -r '.googleClientId')" >> $GITHUB_OUTPUT
        echo "google-client-secret=$(echo "$APP_SECRETS_JSON" | jq -r '.googleClientSecret')" >> $GITHUB_OUTPUT
        echo "initial-user-email=$(echo "$APP_SECRETS_JSON" | jq -r '.initialUserEmail')" >> $GITHUB_OUTPUT
        echo "mongo-admin-password=$(echo "$APP_SECRETS_JSON" | jq -r '.mongoAdminPassword')" >> $GITHUB_OUTPUT
        echo "git-author-name=$(echo "$APP_SECRETS_JSON" | jq -r '.gitSettings.authorName')" >> $GITHUB_OUTPUT
        echo "git-author-email=$(echo "$APP_SECRETS_JSON" | jq -r '.gitSettings.authorEmail')" >> $GITHUB_OUTPUT
        echo "git-token=$(echo "$APP_SECRETS_JSON" | jq -r '.gitSettings.token')" >> $GITHUB_OUTPUT
        echo "git-clone-url=$(echo "$APP_SECRETS_JSON" | jq -r '.gitSettings.cloneUrl')" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -f FestivalManagementWeb/Dockerfile -t ${{ steps.extract-params.outputs.image-name }}:${{ github.sha }} .

    - name: Login to container registry
      run: |
        REGISTRY="${{ steps.extract-params.outputs.container-registry-server }}"
        if [ "$REGISTRY" = "ghcr.io" ]; then
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login "$REGISTRY" --username "${{ github.actor }}" --password-stdin
        else
          echo "Error: Only GHCR (ghcr.io) is supported as container registry"
          exit 1
        fi

    - name: Push Docker image
      run: |
        REPOSITORY="${{ steps.extract-params.outputs.container-registry-repository }}"
        REGISTRY="${{ steps.extract-params.outputs.container-registry-server }}"
        TARGET_IMAGE="$REGISTRY/$REPOSITORY"
        docker tag ${{ steps.extract-params.outputs.image-name }}:${{ github.sha }} $TARGET_IMAGE:${{ github.sha }}
        docker tag ${{ steps.extract-params.outputs.image-name }}:${{ github.sha }} $TARGET_IMAGE:latest
        docker push $TARGET_IMAGE:${{ github.sha }}
        docker push $TARGET_IMAGE:latest

    - name: Make package public
      run: |
        PACKAGE_NAME=$(echo "${{ steps.extract-params.outputs.container-registry-repository }}" | cut -d'/' -f2)
        echo "Setting package visibility to public: $PACKAGE_NAME"

        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/orgs/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" \
          -f visibility='public' || \
        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/users/${{ github.repository_owner }}/packages/container/$PACKAGE_NAME" \
          -f visibility='public'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy infrastructure (Cosmos DB + Environment)
      id: deploy-infrastructure
      run: |
        RESOURCE_GROUP="${{ steps.extract-params.outputs.resource-group }}"
        NAME_PREFIX="${{ steps.extract-params.outputs.name-prefix }}"
        ENV_NAME="${NAME_PREFIX}-env"
        COSMOS_NAME="${NAME_PREFIX}-cosmos"

        # Check if infrastructure already exists
        ENV_EXISTS=false
        COSMOS_EXISTS=false

        if az containerapp env show --name "$ENV_NAME" --resource-group "$RESOURCE_GROUP" &>/dev/null; then
          echo "Container Apps Environment already exists: $ENV_NAME"
          ENV_EXISTS=true
        fi

        if az cosmosdb mongocluster show --cluster-name "$COSMOS_NAME" --resource-group "$RESOURCE_GROUP" &>/dev/null 2>&1; then
          echo "Cosmos DB already exists: $COSMOS_NAME"
          COSMOS_EXISTS=true
        fi

        # Only deploy if something is missing
        if [ "$ENV_EXISTS" = false ] || [ "$COSMOS_EXISTS" = false ]; then
          echo "Deploying missing infrastructure..."
          az deployment group create \
            --name "infra-${{ github.run_number }}-${{ github.run_attempt }}" \
            --resource-group "$RESOURCE_GROUP" \
            --template-file infra/infrastructure.bicep \
            --parameters namePrefix="$NAME_PREFIX" \
            --parameters location="${{ steps.extract-params.outputs.location }}" \
            --parameters mongoAdminPassword="${{ steps.extract-secrets.outputs.mongo-admin-password }}" \
            --output json > infra-output.json

          ENV_ID=$(jq -r '.properties.outputs.environmentId.value' infra-output.json)
          COSMOS_NAME=$(jq -r '.properties.outputs.cosmosDbAccountName.value' infra-output.json)
        else
          echo "All infrastructure already exists, skipping deployment"
          ENV_ID=$(az containerapp env show --name "$ENV_NAME" --resource-group "$RESOURCE_GROUP" --query "id" -o tsv)
        fi

        echo "environmentId=$ENV_ID" >> $GITHUB_OUTPUT
        echo "cosmosDbAccountName=$COSMOS_NAME" >> $GITHUB_OUTPUT

    - name: Deploy or update Container App
      id: deploy-application
      run: |
        APP_NAME="${{ steps.extract-params.outputs.image-name }}"
        RESOURCE_GROUP="${{ steps.extract-params.outputs.resource-group }}"
        IMAGE="${{ steps.extract-params.outputs.container-registry-server }}/${{ steps.extract-params.outputs.container-registry-repository }}:latest"

        # Check if Container App exists
        if az containerapp show --name "$APP_NAME" --resource-group "$RESOURCE_GROUP" &>/dev/null; then
          echo "Container App exists, updating image..."

          # Update image (public image, no authentication)
          az containerapp update \
            --name "$APP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --image "$IMAGE"
        else
          echo "Container App does not exist, creating via Bicep..."
          az deployment group create \
            --name "app-${{ github.run_number }}-${{ github.run_attempt }}" \
            --resource-group "$RESOURCE_GROUP" \
            --template-file infra/application.bicep \
            --parameters containerAppName="$APP_NAME" \
            --parameters location="${{ steps.extract-params.outputs.location }}" \
            --parameters environmentId="${{ steps.deploy-infrastructure.outputs.environmentId }}" \
            --parameters cosmosDbAccountName="${{ steps.deploy-infrastructure.outputs.cosmosDbAccountName }}" \
            --parameters imageTag="latest" \
            --parameters containerRegistryServer="${{ steps.extract-params.outputs.container-registry-server }}" \
            --parameters containerRegistryRepository="${{ steps.extract-params.outputs.container-registry-repository }}"
        fi

        # Get Container App details
        APP_URL=$(az containerapp show --name "$APP_NAME" --resource-group "$RESOURCE_GROUP" --query "properties.configuration.ingress.fqdn" -o tsv)
        PRINCIPAL_ID=$(az containerapp show --name "$APP_NAME" --resource-group "$RESOURCE_GROUP" --query "identity.principalId" -o tsv)

        echo "containerAppUrl=https://$APP_URL" >> $GITHUB_OUTPUT
        echo "containerAppPrincipalId=$PRINCIPAL_ID" >> $GITHUB_OUTPUT

    - name: Configure Container App secrets and environment
      run: |
        echo "Configuring secrets and environment variables..."
        APP_NAME="${{ steps.extract-params.outputs.image-name }}"
        RESOURCE_GROUP="${{ steps.extract-params.outputs.resource-group }}"
        COSMOS_NAME="${{ steps.deploy-infrastructure.outputs.cosmosDbAccountName }}"

        MONGO_CONN="mongodb+srv://mongoAdmin:${{ steps.extract-secrets.outputs.mongo-admin-password }}@${COSMOS_NAME}.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"

        # Set secrets
        az containerapp secret set \
          --name "$APP_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          --secrets \
            mongo-connection-string="$MONGO_CONN" \
            google-client-id="${{ steps.extract-secrets.outputs.google-client-id }}" \
            google-client-secret="${{ steps.extract-secrets.outputs.google-client-secret }}" \
            git-token="${{ steps.extract-secrets.outputs.git-token }}" \
            git-clone-url="${{ steps.extract-secrets.outputs.git-clone-url }}"

        # Update with environment variables
        az containerapp update \
          --name "$APP_NAME" \
          --resource-group "$RESOURCE_GROUP" \
          --set-env-vars \
            ASPNETCORE_ENVIRONMENT=Production \
            MongoDbSettings__ConnectionString=secretref:mongo-connection-string \
            MongoDbSettings__DatabaseName=FestivalManagement \
            Authentication__Google__ClientId=secretref:google-client-id \
            Authentication__Google__ClientSecret=secretref:google-client-secret \
            InitialUser__Email="${{ steps.extract-secrets.outputs.initial-user-email }}" \
            FreeTier__EnableBanner=true \
            FreeTier__BudgetVcpuSeconds=180000 \
            FreeTier__BudgetGiBSeconds=360000 \
            FreeTier__Resource__VcpuPerReplica=0.25 \
            FreeTier__Resource__MemoryGiBPerReplica=0.5 \
            FreeTier__Resource__ReplicaFactor=1 \
            AzureUsage__Enabled=true \
            AzureUsage__ContainerAppName="$APP_NAME" \
            AzureUsage__ResourceGroup="$RESOURCE_GROUP" \
            AzureUsage__SubscriptionId="${{ env.SUBSCRIPTION_ID }}" \
            AzureUsage__MetricsRefreshMinutes=10 \
            FreeTier__Cosmos__Enabled=true \
            FreeTier__Cosmos__SubscriptionId="${{ env.SUBSCRIPTION_ID }}" \
            FreeTier__Cosmos__ResourceGroup="$RESOURCE_GROUP" \
            FreeTier__Cosmos__AccountName="$COSMOS_NAME" \
            FreeTier__Cosmos__DatabaseName=FestivalManagement \
            FreeTier__Cosmos__AccountResourceId="/subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.DocumentDB/mongoClusters/$COSMOS_NAME" \
            FreeTier__EnforceRequestDailyCap=false \
            FreeTier__Data__BudgetGb=100 \
            FreeTier__Requests__Budget=2000000 \
            FreeTier__Cosmos__Provisioning=vCore \
            FreeTier__Cosmos__FreeTierStorageGb=32 \
            FreeTier__Cosmos__FreeTierVCoreStorageGb=32 \
            FreeTier__Cosmos__WarnRuPercent=90 \
            FreeTier__Cosmos__WarnStoragePercent=90 \
            FreeTier__Cosmos__RefreshMinutes=60 \
            AzureUsage__CostRefreshMinutes=360 \
            GitSettings__RemoteName=origin \
            FreeTier__Cosmos__CollectionNames__0=TextKeyValues \
            FreeTier__Cosmos__CollectionNames__1=ImageKeyValues \
            GitSettings__AuthorName="${{ steps.extract-secrets.outputs.git-author-name }}" \
            GitSettings__AuthorEmail="${{ steps.extract-secrets.outputs.git-author-email }}" \
            GitSettings__Token=secretref:git-token \
            GitSettings__CloneUrl=secretref:git-clone-url

    - name: Assign roles to Container App managed identity
      continue-on-error: true
      run: |
        PRINCIPAL_ID="${{ steps.deploy-application.outputs.containerAppPrincipalId }}"
        RESOURCE_GROUP="${{ steps.extract-params.outputs.resource-group }}"

        if [ -z "$PRINCIPAL_ID" ] || [ "$PRINCIPAL_ID" = "null" ]; then
          echo "Warning: Principal ID not found, skipping role assignments"
          exit 0
        fi

        echo "Waiting for managed identity to propagate..."
        sleep 30

        echo "Assigning Reader role..."
        az role assignment create \
          --assignee "$PRINCIPAL_ID" \
          --role "Reader" \
          --scope "/subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/$RESOURCE_GROUP" \
          2>&1 | grep -v "already exists" || true

        echo "Assigning Monitoring Reader role..."
        az role assignment create \
          --assignee "$PRINCIPAL_ID" \
          --role "Monitoring Reader" \
          --scope "/subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/$RESOURCE_GROUP" \
          2>&1 | grep -v "already exists" || true

        echo "Assigning Cost Management Reader role..."
        az role assignment create \
          --assignee "$PRINCIPAL_ID" \
          --role "Cost Management Reader" \
          --scope "/subscriptions/${{ env.SUBSCRIPTION_ID }}" \
          2>&1 | grep -v "already exists" || true

        echo "Role assignments completed"

    - name: Cleanup secrets
      if: always()
      run: rm -f infra/secrets.json

    - name: Output application URL
      run: |
        echo "Application deployed to: ${{ steps.deploy-application.outputs.containerAppUrl }}"

